[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo = 'justmao945/vim-clang'
hook_add = '''
'''

[[plugins]]
repo = 'billyvg/tigris.nvim'
hook_add = '''
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
autocmd FileType c ClangFormatAutoEnable
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
'''
