[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c','cpp','h']
hook_add = '''
  source ~/.config/nvim/plugins/vim-clang.vim
'''

[[plugins]]
repo = 'billyvg/tigris.nvim'
hook_add = '''
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c','cpp','h']
hook_add = '''
  autocmd FileType c ClangFormatAutoEnable
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
'''

[[plugins]]
repo = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install --no-dev -o'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
on_ft = ['php']

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  autocmd FileType html,css,php,jsx EmmetInstall
'''

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  source ~/.config/nvim/plugins/vim-closetag.vim
'''
